# Change these first
owner: Generic-Linux # Your GitHub username
repo: status.genericlinux.org # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Site
    url: https://genericlinux.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.genericlinux.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Generic Linux Status Page"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/Generic-Linux/status.genericlinux.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Main Site
      href: https://genericlinux.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
